// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbm5Bpes84Yky4W5-Ul1CIApw09mR1WIA',
    appId: '1:591417970886:web:6c067e4f9c82a8e6b447c7',
    messagingSenderId: '591417970886',
    projectId: 'spotify-e61af',
    authDomain: 'spotify-e61af.firebaseapp.com',
    storageBucket: 'spotify-e61af.appspot.com',
    measurementId: 'G-SNVGV1F4GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPf0MxZV-TufQtRh7lSVPOGiTQl68nnUc',
    appId: '1:591417970886:android:0719d32d7a14222bb447c7',
    messagingSenderId: '591417970886',
    projectId: 'spotify-e61af',
    storageBucket: 'spotify-e61af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PY2IAToJzmkP44dST1hNbfIJjsQB4Pc',
    appId: '1:591417970886:ios:544b1220d31cb8ccb447c7',
    messagingSenderId: '591417970886',
    projectId: 'spotify-e61af',
    storageBucket: 'spotify-e61af.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5PY2IAToJzmkP44dST1hNbfIJjsQB4Pc',
    appId: '1:591417970886:ios:544b1220d31cb8ccb447c7',
    messagingSenderId: '591417970886',
    projectId: 'spotify-e61af',
    storageBucket: 'spotify-e61af.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbm5Bpes84Yky4W5-Ul1CIApw09mR1WIA',
    appId: '1:591417970886:web:e7333705b09b378cb447c7',
    messagingSenderId: '591417970886',
    projectId: 'spotify-e61af',
    authDomain: 'spotify-e61af.firebaseapp.com',
    storageBucket: 'spotify-e61af.appspot.com',
    measurementId: 'G-6MPVRELXNC',
  );
}
